### PR TITLE
Review and add to toc

### PR DESCRIPTION
**Pull request by pablo-de-andres**

### CODE REVIEW

**Review by unkcpz — APPROVED** [review]
@pablo-de-andres thanks a lot!

**Comment by unkcpz** [comment]
So this one will go first and then the https://github.com/materials-marketplace/user-docs/pull/37?

**Comment by pablo-de-andres** [comment]
There should be no dependency, right?
I just started with this one, it seemed the quicker one.

**Comment by unkcpz** [comment]
Yes, no dependency.

**Pull request merged**
